// Generated by scratchpad/gen-hero-collage.mjs -- a scattered collage of the site's own
// category icons (same lucide set as lib/category-icons.tsx), standing in for "everything that
// can be sold here" without pulling in a licensed stock photo. Blurred + low-opacity so it reads
// as texture behind the hero headline/search bar, never competing with them. Rendered inline
// (not a CSS background-image) so the stroke colors can use the page's own --brand-* custom
// properties and keep adapting in dark mode.
export function HeroCollage() {
  return (
    <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden" aria-hidden="true">
      <svg
        className="h-full w-full"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 1600 340"
        preserveAspectRatio="xMidYMid slice"
      >
        <defs>
          <symbol id="i-car" viewBox="0 0 24 24"><path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"/><circle cx="7" cy="17" r="2"/><path d="M9 17h6"/><circle cx="17" cy="17" r="2"/></symbol>
        <symbol id="i-sofa" viewBox="0 0 24 24"><path d="M20 9V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v3"/><path d="M2 16a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5a2 2 0 0 0-4 0v1.5a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5V11a2 2 0 0 0-4 0z"/><path d="M4 18v2"/><path d="M20 18v2"/><path d="M12 4v9"/></symbol>
        <symbol id="i-laptop" viewBox="0 0 24 24"><path d="M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z"/><path d="M20.054 15.987H3.946"/></symbol>
        <symbol id="i-shirt" viewBox="0 0 24 24"><path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z"/></symbol>
        <symbol id="i-bookOpen" viewBox="0 0 24 24"><path d="M12 5v16"/><path d="M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z"/></symbol>
        <symbol id="i-bike" viewBox="0 0 24 24"><circle cx="18.5" cy="17.5" r="3.5"/><circle cx="5.5" cy="17.5" r="3.5"/><circle cx="15" cy="5" r="1"/><path d="M12 17.5V14l-3-3 4-3 2 3h2"/></symbol>
        <symbol id="i-gamepad" viewBox="0 0 24 24"><line x1="6" x2="10" y1="11" y2="11"/><line x1="8" x2="8" y1="9" y2="13"/><line x1="15" x2="15.01" y1="12" y2="12"/><line x1="18" x2="18.01" y1="10" y2="10"/><path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z"/></symbol>
        <symbol id="i-smartphone" viewBox="0 0 24 24"><rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/></symbol>
        <symbol id="i-house" viewBox="0 0 24 24"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></symbol>
        <symbol id="i-gem" viewBox="0 0 24 24"><path d="M10.5 3 8 9l4 13 4-13-2.5-6"/><path d="M17 3a2 2 0 0 1 1.6.8l3 4a2 2 0 0 1 .013 2.382l-7.99 10.986a2 2 0 0 1-3.247 0l-7.99-10.986A2 2 0 0 1 2.4 7.8l2.998-3.997A2 2 0 0 1 7 3z"/><path d="M2 9h20"/></symbol>
        <symbol id="i-music" viewBox="0 0 24 24"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></symbol>
        <symbol id="i-ticket" viewBox="0 0 24 24"><path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"/><path d="M13 5v2"/><path d="M13 17v2"/><path d="M13 11v2"/></symbol>
        <symbol id="i-pawPrint" viewBox="0 0 24 24"><circle cx="11" cy="4" r="2"/><circle cx="18" cy="8" r="2"/><circle cx="20" cy="16" r="2"/><path d="M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z"/></symbol>
        <symbol id="i-dumbbell" viewBox="0 0 24 24"><path d="M17.596 12.768a2 2 0 1 0 2.829-2.829l-1.768-1.767a2 2 0 0 0 2.828-2.829l-2.828-2.828a2 2 0 0 0-2.829 2.828l-1.767-1.768a2 2 0 1 0-2.829 2.829z"/><path d="m2.5 21.5 1.4-1.4"/><path d="m20.1 3.9 1.4-1.4"/><path d="M5.343 21.485a2 2 0 1 0 2.829-2.828l1.767 1.768a2 2 0 1 0 2.829-2.829l-6.364-6.364a2 2 0 1 0-2.829 2.829l1.768 1.767a2 2 0 0 0-2.828 2.829z"/><path d="m9.6 14.4 4.8-4.8"/></symbol>
        <symbol id="i-washingMachine" viewBox="0 0 24 24"><path d="M3 6h3"/><path d="M17 6h.01"/><rect width="18" height="20" x="3" y="2" rx="2"/><circle cx="12" cy="13" r="5"/><path d="M12 18a2.5 2.5 0 0 0 0-5 2.5 2.5 0 0 1 0-5"/></symbol>
        <symbol id="i-anchor" viewBox="0 0 24 24"><path d="M12 6v16"/><path d="m19 13 2-1a9 9 0 0 1-18 0l2 1"/><path d="M9 11h6"/><circle cx="12" cy="4" r="2"/></symbol>
        <symbol id="i-baby" viewBox="0 0 24 24"><path d="M10 16c.5.3 1.2.5 2 .5s1.5-.2 2-.5"/><path d="M15 12h.01"/><path d="M19.38 6.813A9 9 0 0 1 20.8 10.2a2 2 0 0 1 0 3.6 9 9 0 0 1-17.6 0 2 2 0 0 1 0-3.6A9 9 0 0 1 12 3c2 0 3.5 1.1 3.5 2.5s-.9 2.5-2 2.5c-.8 0-1.5-.4-1.5-1"/><path d="M9 12h.01"/></symbol>
        <symbol id="i-wrench" viewBox="0 0 24 24"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"/></symbol>
        <symbol id="i-building" viewBox="0 0 24 24"><path d="M10 12h4"/><path d="M10 8h4"/><path d="M14 21v-3a2 2 0 0 0-4 0v3"/><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"/><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"/></symbol>
        <symbol id="i-camera" viewBox="0 0 24 24"><path d="M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z"/><circle cx="12" cy="13" r="3"/></symbol>
          <filter id="hero-collage-soften" x="-20%" y="-20%" width="140%" height="140%">
            <feGaussianBlur stdDeviation="3.5" />
          </filter>
        </defs>
        <g fill="none" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" filter="url(#hero-collage-soften)" opacity="0.3">
          <use href="#i-car" x="-12" y="-12" width="24" height="24" transform="translate(55.0 46.4) rotate(23.4) scale(2.89)" stroke="var(--brand-green)" />
          <use href="#i-sofa" x="-12" y="-12" width="24" height="24" transform="translate(190.6 37.4) rotate(-20.9) scale(2.16)" stroke="var(--brand-navy)" />
          <use href="#i-laptop" x="-12" y="-12" width="24" height="24" transform="translate(342.1 57.1) rotate(-11.5) scale(1.62)" stroke="var(--brand-green)" />
          <use href="#i-shirt" x="-12" y="-12" width="24" height="24" transform="translate(480.4 35.8) rotate(17.8) scale(2.11)" stroke="var(--brand-navy)" />
          <use href="#i-bookOpen" x="-12" y="-12" width="24" height="24" transform="translate(684.9 38.0) rotate(22.4) scale(2.82)" stroke="var(--brand-navy)" />
          <use href="#i-bike" x="-12" y="-12" width="24" height="24" transform="translate(808.0 54.8) rotate(21.2) scale(2.16)" stroke="var(--brand-gold)" />
          <use href="#i-gamepad" x="-12" y="-12" width="24" height="24" transform="translate(924.8 30.1) rotate(19.8) scale(2.11)" stroke="var(--brand-navy)" />
          <use href="#i-smartphone" x="-12" y="-12" width="24" height="24" transform="translate(1073.2 37.3) rotate(-18.2) scale(2.48)" stroke="var(--brand-navy)" />
          <use href="#i-house" x="-12" y="-12" width="24" height="24" transform="translate(1226.6 54.9) rotate(-11.9) scale(2.17)" stroke="var(--brand-navy)" />
          <use href="#i-gem" x="-12" y="-12" width="24" height="24" transform="translate(1356.9 51.4) rotate(1.5) scale(1.72)" stroke="var(--brand-green)" />
          <use href="#i-music" x="-12" y="-12" width="24" height="24" transform="translate(1500.8 35.3) rotate(-14.6) scale(1.93)" stroke="var(--brand-navy)" />
          <use href="#i-ticket" x="-12" y="-12" width="24" height="24" transform="translate(54.1 140.7) rotate(-13.1) scale(1.84)" stroke="var(--brand-navy)" />
          <use href="#i-pawPrint" x="-12" y="-12" width="24" height="24" transform="translate(248.0 126.0) rotate(-24.9) scale(2.32)" stroke="var(--brand-navy)" />
          <use href="#i-dumbbell" x="-12" y="-12" width="24" height="24" transform="translate(390.5 139.5) rotate(3.8) scale(2.90)" stroke="var(--brand-green)" />
          <use href="#i-washingMachine" x="-12" y="-12" width="24" height="24" transform="translate(515.9 124.7) rotate(-6.6) scale(2.29)" stroke="var(--brand-green)" />
          <use href="#i-anchor" x="-12" y="-12" width="24" height="24" transform="translate(666.4 122.0) rotate(-24.2) scale(3.06)" stroke="var(--brand-navy)" />
          <use href="#i-baby" x="-12" y="-12" width="24" height="24" transform="translate(816.0 121.3) rotate(0.3) scale(2.52)" stroke="var(--brand-green)" />
          <use href="#i-wrench" x="-12" y="-12" width="24" height="24" transform="translate(970.8 136.1) rotate(-16.5) scale(2.03)" stroke="var(--brand-navy)" />
          <use href="#i-building" x="-12" y="-12" width="24" height="24" transform="translate(1126.3 130.4) rotate(-3.4) scale(2.88)" stroke="var(--brand-gold)" />
          <use href="#i-camera" x="-12" y="-12" width="24" height="24" transform="translate(1226.5 116.9) rotate(-4.5) scale(2.49)" stroke="var(--brand-green)" />
          <use href="#i-car" x="-12" y="-12" width="24" height="24" transform="translate(1347.3 132.9) rotate(11.6) scale(1.76)" stroke="var(--brand-navy)" />
          <use href="#i-sofa" x="-12" y="-12" width="24" height="24" transform="translate(1521.4 132.8) rotate(9.6) scale(2.01)" stroke="var(--brand-navy)" />
          <use href="#i-laptop" x="-12" y="-12" width="24" height="24" transform="translate(52.9 213.7) rotate(-8.1) scale(1.64)" stroke="var(--brand-green)" />
          <use href="#i-shirt" x="-12" y="-12" width="24" height="24" transform="translate(245.0 223.3) rotate(-20.1) scale(1.99)" stroke="var(--brand-gold)" />
          <use href="#i-bookOpen" x="-12" y="-12" width="24" height="24" transform="translate(366.0 195.5) rotate(-23.4) scale(2.80)" stroke="var(--brand-gold)" />
          <use href="#i-bike" x="-12" y="-12" width="24" height="24" transform="translate(503.8 204.4) rotate(-6.4) scale(1.69)" stroke="var(--brand-green)" />
          <use href="#i-gamepad" x="-12" y="-12" width="24" height="24" transform="translate(642.1 216.6) rotate(-10.6) scale(2.26)" stroke="var(--brand-gold)" />
          <use href="#i-smartphone" x="-12" y="-12" width="24" height="24" transform="translate(814.3 216.7) rotate(6.3) scale(2.26)" stroke="var(--brand-navy)" />
          <use href="#i-house" x="-12" y="-12" width="24" height="24" transform="translate(964.0 213.6) rotate(-12.8) scale(1.88)" stroke="var(--brand-gold)" />
          <use href="#i-gem" x="-12" y="-12" width="24" height="24" transform="translate(1115.7 231.7) rotate(-14.0) scale(1.88)" stroke="var(--brand-navy)" />
          <use href="#i-music" x="-12" y="-12" width="24" height="24" transform="translate(1231.2 196.8) rotate(-11.9) scale(1.68)" stroke="var(--brand-navy)" />
          <use href="#i-ticket" x="-12" y="-12" width="24" height="24" transform="translate(1351.7 217.4) rotate(-0.1) scale(1.90)" stroke="var(--brand-navy)" />
          <use href="#i-pawPrint" x="-12" y="-12" width="24" height="24" transform="translate(1552.9 193.8) rotate(12.9) scale(2.18)" stroke="var(--brand-gold)" />
          <use href="#i-dumbbell" x="-12" y="-12" width="24" height="24" transform="translate(89.2 312.3) rotate(24.0) scale(2.11)" stroke="var(--brand-navy)" />
          <use href="#i-washingMachine" x="-12" y="-12" width="24" height="24" transform="translate(234.6 280.1) rotate(17.5) scale(2.57)" stroke="var(--brand-green)" />
          <use href="#i-anchor" x="-12" y="-12" width="24" height="24" transform="translate(332.1 317.2) rotate(24.4) scale(2.69)" stroke="var(--brand-navy)" />
          <use href="#i-baby" x="-12" y="-12" width="24" height="24" transform="translate(480.3 306.7) rotate(-17.4) scale(2.81)" stroke="var(--brand-green)" />
          <use href="#i-wrench" x="-12" y="-12" width="24" height="24" transform="translate(636.4 290.0) rotate(3.7) scale(2.92)" stroke="var(--brand-gold)" />
          <use href="#i-building" x="-12" y="-12" width="24" height="24" transform="translate(797.8 299.9) rotate(0.3) scale(2.29)" stroke="var(--brand-navy)" />
          <use href="#i-camera" x="-12" y="-12" width="24" height="24" transform="translate(932.5 315.0) rotate(-17.8) scale(2.26)" stroke="var(--brand-green)" />
          <use href="#i-car" x="-12" y="-12" width="24" height="24" transform="translate(1093.1 302.9) rotate(-2.8) scale(2.67)" stroke="var(--brand-gold)" />
          <use href="#i-sofa" x="-12" y="-12" width="24" height="24" transform="translate(1249.0 289.6) rotate(15.5) scale(1.81)" stroke="var(--brand-navy)" />
          <use href="#i-laptop" x="-12" y="-12" width="24" height="24" transform="translate(1352.6 300.9) rotate(21.8) scale(2.75)" stroke="var(--brand-green)" />
          <use href="#i-shirt" x="-12" y="-12" width="24" height="24" transform="translate(1513.5 286.1) rotate(-1.6) scale(3.12)" stroke="var(--brand-navy)" />
        </g>
      </svg>
    </div>
  );
}
