alter table profiles
  add column if not exists phone_number varchar(30),
  add column if not exists postal_code varchar(20);

alter table profiles
  add column if not exists account_number bigint generated by default as identity;
