-- Closes the gap between this app's Cars attribute set (10 fields: make/model/year/mileage/fuel/
-- transmission/colour/condition/brand/power) and Marktplaats.nl's real car-listing form (captured
-- live 2026-09-18): body type, emission class, interior, upholstery, curb weight, cylinder count,
-- engine displacement, braked/unbraked towing capacity, maintenance/VAT booleans, and the big
-- "Opties" feature checklist. Only possible now that multi_select and boolean are real, supported
-- data types (lib/categories.ts's SUPPORTED_DATA_TYPES, components/listing-attribute-field.tsx) --
-- this migration is pure data, no further app code changes needed for any of it to render/save.
BEGIN;

-- New single_select/integer attributes.
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('body_type','single_select',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Body Type' FROM attributes WHERE stable_key='body_type' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('emission_class','single_select',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Emission Class' FROM attributes WHERE stable_key='emission_class' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('interior_type','single_select',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Interior' FROM attributes WHERE stable_key='interior_type' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('upholstery','single_select',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Upholstery' FROM attributes WHERE stable_key='upholstery' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('curb_weight','integer','kg') ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Curb Weight' FROM attributes WHERE stable_key='curb_weight' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('cylinder_count','integer',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Cylinders' FROM attributes WHERE stable_key='cylinder_count' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('engine_displacement','integer','cc') ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Engine Displacement' FROM attributes WHERE stable_key='engine_displacement' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('towing_capacity_braked','integer','kg') ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Towing Capacity (Braked)' FROM attributes WHERE stable_key='towing_capacity_braked' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('towing_capacity_unbraked','integer','kg') ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Towing Capacity (Unbraked)' FROM attributes WHERE stable_key='towing_capacity_unbraked' ON CONFLICT DO NOTHING;

-- New boolean attributes (Onderhoud/BTW section).
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('dealer_maintained','boolean',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Dealer Maintained' FROM attributes WHERE stable_key='dealer_maintained' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('maintenance_booklet','boolean',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Maintenance Booklet' FROM attributes WHERE stable_key='maintenance_booklet' ON CONFLICT DO NOTHING;
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('vat_deductible','boolean',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','VAT Deductible' FROM attributes WHERE stable_key='vat_deductible' ON CONFLICT DO NOTHING;

-- The "Opties" feature checklist -- one multi_select attribute, many options.
INSERT INTO attributes(stable_key,data_type,unit_code) VALUES('vehicle_options','multi_select',NULL) ON CONFLICT(stable_key) DO NOTHING;
INSERT INTO attribute_translations(attribute_id,language_code,name) SELECT id,'en','Options' FROM attributes WHERE stable_key='vehicle_options' ON CONFLICT DO NOTHING;

-- Link every new attribute to the Cars category (mirrors 20260101000600's own pattern exactly).
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,true FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='body_type' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,true FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='emission_class' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='interior_type' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='upholstery' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='curb_weight' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='cylinder_count' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='engine_displacement' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='towing_capacity_braked' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='towing_capacity_unbraked' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,true FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='dealer_maintained' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,false FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='maintenance_booklet' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,true FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='vat_deductible' ON CONFLICT DO NOTHING;
INSERT INTO category_attributes(category_id,attribute_id,is_required,is_search_filter) SELECT c.id,a.id,false,true FROM categories c,attributes a WHERE c.stable_key='cars' AND a.stable_key='vehicle_options' ON CONFLICT DO NOTHING;

-- body_type options.
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'hatchback',0 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Hatchback' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'sedan',10 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Sedan' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'estate',20 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Estate / Wagon' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'suv',30 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','SUV / Crossover' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'mpv',40 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','MPV / Minivan' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'coupe',50 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Coupe' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'convertible',60 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Convertible' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'pickup',70 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Pickup' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='body_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'van',80 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Van' FROM o ON CONFLICT DO NOTHING;

-- emission_class options (real Euro emission standards).
WITH x AS (SELECT id FROM attributes WHERE stable_key='emission_class'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'euro6',0 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Euro 6' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='emission_class'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'euro5',10 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Euro 5' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='emission_class'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'euro4',20 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Euro 4' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='emission_class'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'euro3_or_older',30 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Euro 3 or older' FROM o ON CONFLICT DO NOTHING;

-- interior_type options.
WITH x AS (SELECT id FROM attributes WHERE stable_key='interior_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'cloth',0 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Cloth' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='interior_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'leather',10 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Leather' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='interior_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'part_leather',20 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Part Leather' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='interior_type'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'alcantara',30 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Alcantara' FROM o ON CONFLICT DO NOTHING;

-- upholstery options (colour of the interior trim, distinct from the exterior colour attribute).
WITH x AS (SELECT id FROM attributes WHERE stable_key='upholstery'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'black',0 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Black' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='upholstery'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'grey',10 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Grey' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='upholstery'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'beige',20 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Beige' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='upholstery'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'brown',30 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Brown' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='upholstery'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'other',40 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Other' FROM o ON CONFLICT DO NOTHING;

-- vehicle_options: the "Opties" checklist. A representative, real subset of Marktplaats' own list
-- (captured live), not the full 60+ -- covers the options buyers actually filter/search by most.
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'360_camera',0 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','360° Camera' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'abs',10 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','ABS' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'adaptive_cruise_control',20 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Adaptive Cruise Control' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'air_conditioning',30 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Air Conditioning' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'airbags',40 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Airbags' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'alarm',50 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Alarm' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'android_auto',60 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Android Auto' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'apple_carplay',70 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Apple CarPlay' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'bluetooth',80 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Bluetooth' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'climate_control',90 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Climate Control' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'cruise_control',100 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Cruise Control' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'electric_windows',110 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Electric Windows' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'heated_seats',120 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Heated Seats' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'keyless_entry',130 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Keyless Entry' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'lane_departure_warning',140 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Lane Departure Warning' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'led_headlights',150 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','LED Headlights' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'navigation_system',160 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Navigation System' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'panoramic_roof',170 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Panoramic Roof' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'parking_sensors',180 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Parking Sensors' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'rain_sensor',190 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Rain Sensor' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'reversing_camera',200 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Reversing Camera' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'sunroof',210 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Sunroof' FROM o ON CONFLICT DO NOTHING;
WITH x AS (SELECT id FROM attributes WHERE stable_key='vehicle_options'), o AS (INSERT INTO attribute_options(attribute_id,stable_key,sort_order) SELECT id,'tow_bar',220 FROM x ON CONFLICT(attribute_id,stable_key) DO UPDATE SET sort_order=EXCLUDED.sort_order RETURNING id) INSERT INTO attribute_option_translations(option_id,language_code,label) SELECT id,'en','Tow Bar' FROM o ON CONFLICT DO NOTHING;

COMMIT;
