-- Generated: full Children & Babies taxonomy, replacing the old 6 flat leaves with 11
-- mid-level groups and their real leaf categories (translated from the Marktplaats
-- 'Kinderen en Baby's' reference the user shared). Old leaves had zero listings/attribute
-- mappings (confirmed before writing this), so removed outright rather than reparented.
DELETE FROM category_translations WHERE category_id IN (
  SELECT id FROM categories WHERE stable_key IN (
    'children-babies-baby-clothing', 'children-babies-childrens-clothing',
    'children-babies-prams', 'children-babies-car-seats',
    'children-babies-nursery-furniture', 'children-babies-toys'
  )
);
DELETE FROM categories WHERE stable_key IN (
  'children-babies-baby-clothing', 'children-babies-childrens-clothing',
  'children-babies-prams', 'children-babies-car-seats',
  'children-babies-nursery-furniture', 'children-babies-toys'
);

-- Baby Essentials
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-baby-essentials', 2, 10, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby Essentials', 'children-babies-baby-essentials' FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-baby-monitors', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby monitors', 'children-babies-baby-essentials-baby-monitors' FROM categories WHERE stable_key = 'children-babies-baby-essentials-baby-monitors';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-baby-food-and-accessories', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby food and accessories', 'children-babies-baby-essentials-baby-food-and-accessories' FROM categories WHERE stable_key = 'children-babies-baby-essentials-baby-food-and-accessories';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-baby-cribs-and-cots', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby cribs and cots', 'children-babies-baby-essentials-baby-cribs-and-cots' FROM categories WHERE stable_key = 'children-babies-baby-essentials-baby-cribs-and-cots';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-baby-baths-and-care', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby baths and care', 'children-babies-baby-essentials-baby-baths-and-care' FROM categories WHERE stable_key = 'children-babies-baby-essentials-baby-baths-and-care';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-blankets-and-sleeping-bags', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Blankets and sleeping bags', 'children-babies-baby-essentials-blankets-and-sleeping-bags' FROM categories WHERE stable_key = 'children-babies-baby-essentials-blankets-and-sleeping-bags';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-birth-gifts-and-announcement-boards', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Birth gifts and announcement boards', 'children-babies-baby-essentials-birth-gifts-and-announcement-boards' FROM categories WHERE stable_key = 'children-babies-baby-essentials-birth-gifts-and-announcement-boards';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-essentials-twins-and-multiples', 3, 70, true, true FROM categories WHERE stable_key = 'children-babies-baby-essentials';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Twins and multiples', 'children-babies-baby-essentials-twins-and-multiples' FROM categories WHERE stable_key = 'children-babies-baby-essentials-twins-and-multiples';

-- Baby Clothing
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-baby-clothing', 2, 20, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby Clothing', 'children-babies-baby-clothing' FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-50', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 50', 'children-babies-baby-clothing-size-50' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-50';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-56', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 56', 'children-babies-baby-clothing-size-56' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-56';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-62', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 62', 'children-babies-baby-clothing-size-62' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-62';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-68', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 68', 'children-babies-baby-clothing-size-68' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-68';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-74', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 74', 'children-babies-baby-clothing-size-74' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-74';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-80', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 80', 'children-babies-baby-clothing-size-80' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-80';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-size-86', 3, 70, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 86', 'children-babies-baby-clothing-size-86' FROM categories WHERE stable_key = 'children-babies-baby-clothing-size-86';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-baby-clothing-sets', 3, 80, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby clothing sets', 'children-babies-baby-clothing-baby-clothing-sets' FROM categories WHERE stable_key = 'children-babies-baby-clothing-baby-clothing-sets';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-baby-swimwear', 3, 90, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby swimwear', 'children-babies-baby-clothing-baby-swimwear' FROM categories WHERE stable_key = 'children-babies-baby-clothing-baby-swimwear';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-hats-scarves-and-mittens', 3, 100, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Hats, scarves and mittens', 'children-babies-baby-clothing-hats-scarves-and-mittens' FROM categories WHERE stable_key = 'children-babies-baby-clothing-hats-scarves-and-mittens';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-caps-and-hats', 3, 110, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Caps and hats', 'children-babies-baby-clothing-caps-and-hats' FROM categories WHERE stable_key = 'children-babies-baby-clothing-caps-and-hats';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-premature', 3, 120, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Premature', 'children-babies-baby-clothing-premature' FROM categories WHERE stable_key = 'children-babies-baby-clothing-premature';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-shoes-and-socks', 3, 130, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Shoes and socks', 'children-babies-baby-clothing-shoes-and-socks' FROM categories WHERE stable_key = 'children-babies-baby-clothing-shoes-and-socks';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-baby-clothing-other-baby-clothing', 3, 140, true, true FROM categories WHERE stable_key = 'children-babies-baby-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Other baby clothing', 'children-babies-baby-clothing-other-baby-clothing' FROM categories WHERE stable_key = 'children-babies-baby-clothing-other-baby-clothing';

-- Indoor Toys
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-indoor-toys', 2, 30, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Indoor Toys', 'children-babies-indoor-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-action-figures', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Action figures', 'children-babies-indoor-toys-action-figures' FROM categories WHERE stable_key = 'children-babies-indoor-toys-action-figures';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-baby-toys', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby toys', 'children-babies-indoor-toys-baby-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys-baby-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-bath-toys', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Bath toys', 'children-babies-indoor-toys-bath-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys-bath-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-building-blocks', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Building blocks', 'children-babies-indoor-toys-building-blocks' FROM categories WHERE stable_key = 'children-babies-indoor-toys-building-blocks';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-duplo-and-lego', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Duplo and Lego', 'children-babies-indoor-toys-duplo-and-lego' FROM categories WHERE stable_key = 'children-babies-indoor-toys-duplo-and-lego';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-educational-and-creative-toys', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Educational and creative toys', 'children-babies-indoor-toys-educational-and-creative-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys-educational-and-creative-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-fisher-price', 3, 70, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Fisher-Price', 'children-babies-indoor-toys-fisher-price' FROM categories WHERE stable_key = 'children-babies-indoor-toys-fisher-price';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-rocking-figures', 3, 80, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Rocking figures', 'children-babies-indoor-toys-rocking-figures' FROM categories WHERE stable_key = 'children-babies-indoor-toys-rocking-figures';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-wooden-toys', 3, 90, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Wooden toys', 'children-babies-indoor-toys-wooden-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys-wooden-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-puzzles', 3, 100, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Puzzles', 'children-babies-indoor-toys-puzzles' FROM categories WHERE stable_key = 'children-babies-indoor-toys-puzzles';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-cuddly-toys-and-plush', 3, 110, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Cuddly toys and plush', 'children-babies-indoor-toys-cuddly-toys-and-plush' FROM categories WHERE stable_key = 'children-babies-indoor-toys-cuddly-toys-and-plush';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-my-little-pony', 3, 120, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'My Little Pony', 'children-babies-indoor-toys-my-little-pony' FROM categories WHERE stable_key = 'children-babies-indoor-toys-my-little-pony';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-playmobil', 3, 130, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Playmobil', 'children-babies-indoor-toys-playmobil' FROM categories WHERE stable_key = 'children-babies-indoor-toys-playmobil';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-dolls', 3, 140, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Dolls', 'children-babies-indoor-toys-dolls' FROM categories WHERE stable_key = 'children-babies-indoor-toys-dolls';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-dollhouses', 3, 150, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Dollhouses', 'children-babies-indoor-toys-dollhouses' FROM categories WHERE stable_key = 'children-babies-indoor-toys-dollhouses';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-race-tracks', 3, 160, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Race tracks', 'children-babies-indoor-toys-race-tracks' FROM categories WHERE stable_key = 'children-babies-indoor-toys-race-tracks';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-ride-on-toys', 3, 170, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Ride-on toys', 'children-babies-indoor-toys-ride-on-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys-ride-on-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-play-houses', 3, 180, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play houses', 'children-babies-indoor-toys-play-houses' FROM categories WHERE stable_key = 'children-babies-indoor-toys-play-houses';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-play-kitchens', 3, 190, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play kitchens', 'children-babies-indoor-toys-play-kitchens' FROM categories WHERE stable_key = 'children-babies-indoor-toys-play-kitchens';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-play-furniture', 3, 200, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play furniture', 'children-babies-indoor-toys-play-furniture' FROM categories WHERE stable_key = 'children-babies-indoor-toys-play-furniture';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-play-tables', 3, 210, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play tables', 'children-babies-indoor-toys-play-tables' FROM categories WHERE stable_key = 'children-babies-indoor-toys-play-tables';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-play-tents', 3, 220, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play tents', 'children-babies-indoor-toys-play-tents' FROM categories WHERE stable_key = 'children-babies-indoor-toys-play-tents';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-thomas-the-train', 3, 230, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Thomas the Train', 'children-babies-indoor-toys-thomas-the-train' FROM categories WHERE stable_key = 'children-babies-indoor-toys-thomas-the-train';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-football-tables', 3, 240, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Football tables', 'children-babies-indoor-toys-football-tables' FROM categories WHERE stable_key = 'children-babies-indoor-toys-football-tables';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-vtech', 3, 250, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Vtech', 'children-babies-indoor-toys-vtech' FROM categories WHERE stable_key = 'children-babies-indoor-toys-vtech';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-indoor-toys-other-indoor-toys', 3, 260, true, true FROM categories WHERE stable_key = 'children-babies-indoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Other indoor toys', 'children-babies-indoor-toys-other-indoor-toys' FROM categories WHERE stable_key = 'children-babies-indoor-toys-other-indoor-toys';

-- Books
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-books', 2, 40, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Books', 'children-babies-books' FROM categories WHERE stable_key = 'children-babies-books';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-books-pregnancy-and-parenting', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-books';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Pregnancy and parenting', 'children-babies-books-pregnancy-and-parenting' FROM categories WHERE stable_key = 'children-babies-books-pregnancy-and-parenting';

-- Outdoor Toys
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-outdoor-toys', 2, 50, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Outdoor Toys', 'children-babies-outdoor-toys' FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-ride-on-vehicles', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Ride-on vehicles', 'children-babies-outdoor-toys-ride-on-vehicles' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-ride-on-vehicles';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-action-toys', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Action toys', 'children-babies-outdoor-toys-action-toys' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-action-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-tricycles', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Tricycles', 'children-babies-outdoor-toys-tricycles' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-tricycles';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-loose-outdoor-toys', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Loose outdoor toys', 'children-babies-outdoor-toys-loose-outdoor-toys' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-loose-outdoor-toys';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-inflatables', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Inflatables', 'children-babies-outdoor-toys-inflatables' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-inflatables';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-roller-skates', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Roller skates', 'children-babies-outdoor-toys-roller-skates' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-roller-skates';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-skeelers', 3, 70, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Skeelers', 'children-babies-outdoor-toys-skeelers' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-skeelers';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-go-karts', 3, 80, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Go-karts', 'children-babies-outdoor-toys-go-karts' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-go-karts';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-sledges', 3, 90, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Sledges', 'children-babies-outdoor-toys-sledges' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-sledges';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-play-houses-outdoor', 3, 100, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play houses (outdoor)', 'children-babies-outdoor-toys-play-houses-outdoor' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-play-houses-outdoor';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-play-tables-outdoor', 3, 110, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play tables (outdoor)', 'children-babies-outdoor-toys-play-tables-outdoor' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-play-tables-outdoor';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-play-equipment', 3, 120, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Play equipment', 'children-babies-outdoor-toys-play-equipment' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-play-equipment';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-bouncy-castles', 3, 130, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Bouncy castles', 'children-babies-outdoor-toys-bouncy-castles' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-bouncy-castles';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-pogo-sticks-and-steps', 3, 140, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Pogo sticks and steps', 'children-babies-outdoor-toys-pogo-sticks-and-steps' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-pogo-sticks-and-steps';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-trampolines', 3, 150, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Trampolines', 'children-babies-outdoor-toys-trampolines' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-trampolines';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-ride-on-and-walking-vehicles', 3, 160, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Ride-on and walking vehicles', 'children-babies-outdoor-toys-ride-on-and-walking-vehicles' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-ride-on-and-walking-vehicles';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-sandboxes', 3, 170, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Sandboxes', 'children-babies-outdoor-toys-sandboxes' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-sandboxes';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-outdoor-toys-pools', 3, 180, true, true FROM categories WHERE stable_key = 'children-babies-outdoor-toys';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Pools', 'children-babies-outdoor-toys-pools' FROM categories WHERE stable_key = 'children-babies-outdoor-toys-pools';

-- Services & Professionals
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-services-professionals', 2, 60, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Services & Professionals', 'children-babies-services-professionals' FROM categories WHERE stable_key = 'children-babies-services-professionals';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-services-professionals-children-s-parties-and-entertainers', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-services-professionals';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s parties and entertainers', 'children-babies-services-professionals-children-s-parties-and-entertainers' FROM categories WHERE stable_key = 'children-babies-services-professionals-children-s-parties-and-entertainers';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-services-professionals-babysitting-and-childcare', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-services-professionals';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Babysitting and childcare', 'children-babies-services-professionals-babysitting-and-childcare' FROM categories WHERE stable_key = 'children-babies-services-professionals-babysitting-and-childcare';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-services-professionals-home-help-and-maternity-care', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-services-professionals';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Home help and maternity care', 'children-babies-services-professionals-home-help-and-maternity-care' FROM categories WHERE stable_key = 'children-babies-services-professionals-home-help-and-maternity-care';

-- Children's Clothing
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-children-s-clothing', 2, 70, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s Clothing', 'children-babies-children-s-clothing' FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-92', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 92', 'children-babies-children-s-clothing-size-92' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-92';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-98', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 98', 'children-babies-children-s-clothing-size-98' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-98';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-104', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 104', 'children-babies-children-s-clothing-size-104' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-104';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-110', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 110', 'children-babies-children-s-clothing-size-110' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-110';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-116', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 116', 'children-babies-children-s-clothing-size-116' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-116';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-122', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 122', 'children-babies-children-s-clothing-size-122' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-122';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-128', 3, 70, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 128', 'children-babies-children-s-clothing-size-128' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-128';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-134', 3, 80, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 134', 'children-babies-children-s-clothing-size-134' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-134';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-140', 3, 90, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 140', 'children-babies-children-s-clothing-size-140' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-140';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-146', 3, 100, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 146', 'children-babies-children-s-clothing-size-146' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-146';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-152', 3, 110, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 152', 'children-babies-children-s-clothing-size-152' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-152';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-158', 3, 120, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 158', 'children-babies-children-s-clothing-size-158' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-158';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-164', 3, 130, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 164', 'children-babies-children-s-clothing-size-164' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-164';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-170', 3, 140, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 170', 'children-babies-children-s-clothing-size-170' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-170';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-size-176', 3, 150, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Size 176', 'children-babies-children-s-clothing-size-176' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-size-176';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-carnival-and-dress-up-clothing', 3, 160, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Carnival and dress-up clothing', 'children-babies-children-s-clothing-carnival-and-dress-up-clothing' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-carnival-and-dress-up-clothing';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-children-s-clothing-sets', 3, 170, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s clothing sets', 'children-babies-children-s-clothing-children-s-clothing-sets' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-children-s-clothing-sets';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-children-s-swimwear', 3, 180, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s swimwear', 'children-babies-children-s-clothing-children-s-swimwear' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-children-s-swimwear';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-hats-scarves-and-mittens', 3, 190, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Hats, scarves and mittens', 'children-babies-children-s-clothing-hats-scarves-and-mittens' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-hats-scarves-and-mittens';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-caps-and-hats', 3, 200, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Caps and hats', 'children-babies-children-s-clothing-caps-and-hats' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-caps-and-hats';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-shoes-and-socks', 3, 210, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Shoes and socks', 'children-babies-children-s-clothing-shoes-and-socks' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-shoes-and-socks';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-clothing-other-children-s-clothing', 3, 220, true, true FROM categories WHERE stable_key = 'children-babies-children-s-clothing';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Other children''s clothing', 'children-babies-children-s-clothing-other-children-s-clothing' FROM categories WHERE stable_key = 'children-babies-children-s-clothing-other-children-s-clothing';

-- Children's Furniture
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-children-s-furniture', 2, 80, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s Furniture', 'children-babies-children-s-furniture' FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-beds', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Beds', 'children-babies-children-s-furniture-beds' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-beds';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-storage-boxes-and-chests', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Storage boxes and chests', 'children-babies-children-s-furniture-storage-boxes-and-chests' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-storage-boxes-and-chests';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-bedding', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Bedding', 'children-babies-children-s-furniture-bedding' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-bedding';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-dressers-and-cabinets', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Dressers and cabinets', 'children-babies-children-s-furniture-dressers-and-cabinets' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-dressers-and-cabinets';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-complete-children-s-rooms', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Complete children''s rooms', 'children-babies-children-s-furniture-complete-children-s-rooms' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-complete-children-s-rooms';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-decor-and-interior', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Decor and interior', 'children-babies-children-s-furniture-decor-and-interior' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-decor-and-interior';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-children-s-decor-items', 3, 70, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s decor items', 'children-babies-children-s-furniture-children-s-decor-items' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-children-s-decor-items';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-children-s-chairs', 3, 80, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s chairs', 'children-babies-children-s-furniture-children-s-chairs' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-children-s-chairs';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-bunk-beds-and-high-sleepers', 3, 90, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Bunk beds and high sleepers', 'children-babies-children-s-furniture-bunk-beds-and-high-sleepers' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-bunk-beds-and-high-sleepers';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-tables-and-chairs', 3, 100, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Tables and chairs', 'children-babies-children-s-furniture-tables-and-chairs' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-tables-and-chairs';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-high-chairs', 3, 110, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'High chairs', 'children-babies-children-s-furniture-high-chairs' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-high-chairs';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-children-s-furniture-other-children-s-furniture', 3, 120, true, true FROM categories WHERE stable_key = 'children-babies-children-s-furniture';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Other children''s furniture', 'children-babies-children-s-furniture-other-children-s-furniture' FROM categories WHERE stable_key = 'children-babies-children-s-furniture-other-children-s-furniture';

-- Fashion Accessories
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-fashion-accessories', 2, 90, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Fashion Accessories', 'children-babies-fashion-accessories' FROM categories WHERE stable_key = 'children-babies-fashion-accessories';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-fashion-accessories-baby-fashion-accessories', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-fashion-accessories';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby fashion accessories', 'children-babies-fashion-accessories-baby-fashion-accessories' FROM categories WHERE stable_key = 'children-babies-fashion-accessories-baby-fashion-accessories';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-fashion-accessories-children-s-fashion-accessories', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-fashion-accessories';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Children''s fashion accessories', 'children-babies-fashion-accessories-children-s-fashion-accessories' FROM categories WHERE stable_key = 'children-babies-fashion-accessories-children-s-fashion-accessories';

-- On the Go
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-on-the-go', 2, 100, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'On the Go', 'children-babies-on-the-go' FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-on-the-go-car-seats', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Car seats', 'children-babies-on-the-go-car-seats' FROM categories WHERE stable_key = 'children-babies-on-the-go-car-seats';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-on-the-go-baby-carriers', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Baby carriers', 'children-babies-on-the-go-baby-carriers' FROM categories WHERE stable_key = 'children-babies-on-the-go-baby-carriers';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-on-the-go-buggies', 3, 30, true, true FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Buggies', 'children-babies-on-the-go-buggies' FROM categories WHERE stable_key = 'children-babies-on-the-go-buggies';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-on-the-go-buggy-accessories', 3, 40, true, true FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Buggy accessories', 'children-babies-on-the-go-buggy-accessories' FROM categories WHERE stable_key = 'children-babies-on-the-go-buggy-accessories';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-on-the-go-strollers', 3, 50, true, true FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Strollers', 'children-babies-on-the-go-strollers' FROM categories WHERE stable_key = 'children-babies-on-the-go-strollers';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-on-the-go-diaper-bags', 3, 60, true, true FROM categories WHERE stable_key = 'children-babies-on-the-go';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Diaper bags', 'children-babies-on-the-go-diaper-bags' FROM categories WHERE stable_key = 'children-babies-on-the-go-diaper-bags';

-- Other
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) VALUES ((SELECT id FROM categories WHERE stable_key = 'children-babies'), 'children-babies-other', 2, 110, true, true);
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Other', 'children-babies-other' FROM categories WHERE stable_key = 'children-babies-other';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-other-watches', 3, 10, true, true FROM categories WHERE stable_key = 'children-babies-other';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Watches', 'children-babies-other-watches' FROM categories WHERE stable_key = 'children-babies-other-watches';
INSERT INTO categories(parent_id, stable_key, level, sort_order, is_active, allows_listings) SELECT id, 'children-babies-other-other-children-baby-items', 3, 20, true, true FROM categories WHERE stable_key = 'children-babies-other';
INSERT INTO category_translations(category_id, language_code, name, slug) SELECT id, 'en', 'Other children & baby items', 'children-babies-other-other-children-baby-items' FROM categories WHERE stable_key = 'children-babies-other-other-children-baby-items';
